# Setup
title:        Kyle Horne's Portfolio
tagline:      Programming Projects
baseurl:      /
paginate:     1

# About/contact
author:
  name:       Kyle Horne
  url:        https://kyle-horne.github.io/about

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title
